---
- hosts: appserver

  tasks:
  - name: install nginx
    apt_repository:
      repo: 'ppa:nginx/stable'
      update_cache: true
    apt: pkg=nginx state=installed
    notify:
      - start nginx

  - name: install let's encrypt certbot
    apt_repository:
      repo: 'ppa:certbot/certbot'
      update_cache: true
    apt: pkg=python-certbot-nginx state=installed
    notify:
      - configure certbot

  - name: install redis
    apt: pkg=redis state=installed
    # configure a randomly selected password as the REQUIREAUTH parameter
    notify:
      - start redis

  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: start redis
      service: name=redis state=started
